name: Spear Core Save Test Results
description: A GitHub action to store test results in S3
branding:
  icon: check-circle
  color: green
inputs:
  s3Bucket:
    description: The S3 Bucket
    required: true
  projectKey:
    description: The project identifier or key
    required: true
  releaseTag:
    description: The release tag or branch
    required: true
  sourceDir:
    description: Target Directory
    required: true
  

runs:
  using: 'composite'
  steps:
    - name: Prepare Source Directory
      shell: bash
      run: |
        [ -d "${{ inputs.sourceDir }}/databases" ] && rm -rf "${{ inputs.sourceDir }}/databases" || true
        git log -1 > "${{ inputs.sourceDir }}/git-status.txt"
        echo "$s3Target" > "${{ inputs.sourceDir }}/s3-path.txt"

    - name: Save Test Results
      shell: bash
      run: |
        s3Target="s3://${{ inputs.s3Bucket }}/${{ inputs.projectKey }}/${{ inputs.releaseTag }}"

        echo "Uploading to $s3Target"
        aws s3 sync --only-show-errors --delete --acl=public-read "./${{ inputs.sourceDir }}" "$s3Target" && \

        # releases/production/2020-01-01 -> releases/production/latest
        if [[ "${{ inputs.releaseTag }}" =~ ^releases/ ]]
        then
          latestPath="s3://${{ inputs.s3Bucket }}/${{ inputs.projectKey }}/releases/$(echo "${{ inputs.releaseTag }}" | cut -d/ -f2)/latest"
          echo "Updating $latestPath"
          aws s3 sync --only-show-errors --delete --acl=public-read "$s3Target" "$latestPath"
        fi


